package main

import (
	"log"
	"time"

	"github.com/pkg/profile"

	"github.com/brunorene/adventofcode2023/day21"
)

//nolint:funlen // its ok
func main() {
	defer profile.Start(profile.ProfilePath(".")).Stop()

	start := time.Now()
	// log.Printf("day01 part1: %v (%v)", day01.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day01 part2: %v (%v)", day01.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day02 part1: %v (%v)", day02.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day02 part2: %v (%v)", day02.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day03 part1: %v (%v)", day03.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day03 part2: %v (%v)", day03.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day04 part1: %v (%v)", day04.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day04 part2: %v (%v)", day04.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day05 part1: %v (%v)", day05.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day05 part2: %v (%v)", day05.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day06 part1: %v (%v)", day06.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day06 part2: %v (%v)", day06.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day07 part1: %v (%v)", day07.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day07 part2: %v (%v)", day07.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day08 part1: %v (%v)", day08.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day08 part2: %v (%v)", day08.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day09 part1: %v (%v)", day09.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day09 part2: %v (%v)", day09.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day10 part1: %v (%v)", day10.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day10 part2: %v (%v)", day10.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day11 part1: %v (%v)", day11.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day11 part2: %v (%v)", day11.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day12 part1: %v (%v)", day12.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day12 part2: %v (%v)", day12.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day13 part1: %v (%v)", day13.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day13 part2: %v (%v)", day13.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day14 part1: %v (%v)", day14.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day14 part2: %v (%v)", day14.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day15 part1: %v (%v)", day15.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day15 part2: %v (%v)", day15.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day16 part1: %v (%v)", day16.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day16 part2: %v (%v)", day16.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day17 part1: %v (%v)", day17.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day18 part1: %v (%v)", day18.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day18 part2: %v (%v)", day18.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day19 part1: %v (%v)", day19.Part1(), time.Since(start))
	// start = time.Now()
	// log.Printf("day19 part2: %v (%v)", day19.Part2(), time.Since(start))
	// start = time.Now()
	// log.Printf("day20 part1: %v (%v)", day20.Part1(), time.Since(start))
	// start = time.Now()
	log.Printf("day21 part1: %v (%v)", day21.Part1(), time.Since(start))
	start = time.Now()
	log.Printf("day21 part2: %v (%v)", day21.Part2(), time.Since(start))
}
